### ISSUE TITLE
Pass Lighthouse validation

### ISSUE THREAD

**Issue by JasonYao** [JasonYao/deprecated-old-2017-site#20]
## Test Generation Command
```sh
lighthouse https://www.jasonyao.com/amp/projects/2017/05/30/gomark-a-github-markdown-renderer/ --view
```

## TODO
- [x] Implement a service worker with precache (#29 )
- [ ] Convert all images to be of the [webP format](https://developers.google.com/web/tools/lighthouse/audits/webp)
- [ ] [Optimize images](https://developers.google.com/web/tools/lighthouse/audits/optimize-images)
- [ ] Properly [size images](https://developers.google.com/web/tools/lighthouse/audits/oversized-images)
- Add in https://github.com/BBC-News/Imager.js/
- [ ] Make the following stylesheets [download async](https://developers.google.com/web/tools/lighthouse/audits/blocking-resources) since they're blocking for about a second:
  - [ ] Font awesome.min
  - [ ] Google fonts
- [ ] Add in an offline message listing some articles in the cache

## Next TODO
- [ ] Make a task runner to generate smaller favicons from a source image
- [ ] Add service worker to AMP
